<script src="<?=base_url('js/jquery.min.js');?>"></script>
    <!-- Bootstrap -->
    <script src="<?=base_url('js/bootstrap.min.js');?>"></script>
    <!-- FastClick -->
    <script src="<?=base_url('js/fastclick.js');?>"></script>
    <!-- NProgress -->
    <script src="<?=base_url('js/nprogress.js');?>"></script>
    <!-- Chart.js -->
    <script src="<?=base_url('js/Chart.min.js');?>"></script>
    <!-- gauge.js -->
    <script src="<?=base_url('js/gauge.min.js');?>"></script>
    <!-- bootstrap-progressbar -->
    <script src="<?=base_url('js/bootstrap-progressbar.min.js');?>"></script>
    <!-- iCheck -->
    <script src="<?=base_url('js/icheck.min.js');?>"></script>
    <!-- Skycons -->
    <script src="<?=base_url('js/skycons.js');?>"></script>
    <!-- Flot -->
    <script src="<?=base_url('Flot/jquery.flot.js');?>"></script>
    <script src="<?=base_url('Flot/jquery.flot.pie.js');?>"></script>
    <script src="<?=base_url('Flot/jquery.flot.time.js');?>"></script>
    <script src="<?=base_url('Flot/jquery.flot.stack.js');?>"></script>
    <script src="<?=base_url('Flot/jquery.flot.resize.js');?>"></script>
    <!-- Flot plugins -->
    <script src="<?=base_url('js/jquery.flot.orderBars.js');?>"></script>
    <script src="<?=base_url('js/jquery.flot.spline.min.js');?>"></script>
    <script src="<?=base_url('js/curvedLines.js');?>"></script>
    <!-- DateJS -->
    <script src="<?=base_url('js/date.js');?>"></script>
    <!-- JQVMap -->
    <script src="<?=base_url('js/jquery.vmap.js');?>"></script>
    <script src="<?=base_url('js/jquery.vmap.world.js');?>"></script>
    <script src="<?=base_url('js/jquery.vmap.sampledata.js');?>"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="<?=base_url('js/moment.min.js');?>"></script>
    <script src="<?=base_url('js/daterangepicker.js');?>"></script>

    <!-- Custom Theme Scripts -->
    <script src="<?=base_url('js/custom.min.js');?>"></script>